kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '3'
  creationTimestamp: '2022-11-02T13:42:50Z'
  generation: 3
  labels:
    app: hedgeDoc
    io.kompose.service: app
    template: hedgeDoc
  name: app
  namespace: csc-hedgedoc
  resourceVersion: '1694240075'
  selfLink: /apis/apps/v1/namespaces/csc-hedgedoc/deployments/app
  uid: 3e210f32-5ab4-11ed-a890-fa163e081ad5
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      io.kompose.service: app
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
        - env:
            - name: CMD_DOMAIN
              value: cschedgedoc.rahtiapp.fi
            - name: CMD_URL_ADDPORT
              value: 'false'
            - name: CMD_PROTOCOL_USESSL
              value: 'true'
            - name: CMD_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: postgresql
            - name: CMD_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: postgresql
            - name: CMD_DB_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: postgresql
            - name: CMD_DB_HOST
              value: postgresql
            - name: CMD_DB_PORT
              value: '5432'
            - name: CMD_DB_DIALECT
              value: postgres
            - name: CMD_ALLOW_FREEURL
              value: 'true'
          image: 'quay.io/hedgedoc/hedgedoc:1.9.4'
          imagePullPolicy: IfNotPresent
          name: app
          ports:
            - containerPort: 3000
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /hedgedoc/public/uploads
              name: uploads
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: uploads
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2022-11-03T12:21:25Z'
      lastUpdateTime: '2022-11-03T12:21:25Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2022-11-02T13:42:50Z'
      lastUpdateTime: '2022-11-03T12:21:25Z'
      message: ReplicaSet "app-66678d56f7" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
